image: node:latest

before_script:
  - npm install -g selenium-side-runner

stages:
  # - deploy
  - confidence-check
  # - test


# deploy:
#   stage: deploy
#   script:
#     - "git pull origin $CI_COMMIT_REF_NAME"
#     - "COMMIT_HASH=$(git rev-parse HEAD)"
#     - "COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)"
#     - "CURRENT_BRANCH=$CI_COMMIT_REF_NAME"
#     - "CHANGES=$(git diff --name-only HEAD^..HEAD /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/html)"

#     - >
#       if [ "$CURRENT_BRANCH" != "Sprint8" ]; then
#         echo "No changes on branch, skipping"
#       elif [ -z "$CHANGES" ]; then
#         echo "No changes in the HTML folder. Commit message: $COMMIT_MESSAGE" 
#       else
#         sudo chmod +w /var/www/html
#         sudo cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/html/* /var/www/html/
#         echo "Recent Commit Deployed: $COMMIT_HASH - $COMMIT_MESSAGE"
#       fi

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - npm run confidence-check --host=selenium__standalone-chrome

# test:
#   stage: test
#   script:
#     - apt-get update -qy
#     - apt-get install -y unzip
#     - wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
#     - unzip chromedriver_linux64.zip
#     - mv chromedriver /usr/local/bin/
#     - chmod +x /usr/local/bin/chromedriver
#     - selenium-side-runner -c "goog:chromeOptions.args=[disable-infobars, headless]" ./sprint9/sprint9_docs/Testing-UI/Sprint7.side
#     # - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/e2eTest
  