image: ubuntu:latest

before_script:
  - apt install -y openssh-client openssh-server

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - ./deploy.sh
  only:
    - testing-ci
