stages:
  - deploy
  # - test
deploy:
  stage: deploy
  script:
    - "git pull origin $CI_COMMIT_REF_NAME"
    - "COMMIT_HASH=$(git rev-parse HEAD)"
    - "COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)"
    - sudo chmod +w /var/www/html
    - sudo cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/html/* /var/www/html/

# test:
#   stage: test
#   script: 
#     - cd;cd ../../
#     - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/e2eTest