stages:
  - test
  - deploy

variables:
  SELENIUM_VERSION: 3.141.59 

before_script:
  - wget https://selenium-release.storage.googleapis.com/$SELENIUM_VERSION/selenium-server-standalone-$SELENIUM_VERSION.jar
  - wget https://github.com/SeleniumHQ/selenium/raw/main/javascript/node/selenium-side-runner/lib/cli/cli.js -O selenium-side-runner
  - chmod +x selenium-side-runner
  - export PATH=$PATH:$CI_PROJECT_DIR  # Add project directory to the PATH

test:
  script:
    - selenium-side-runner ./sprint9/sprint9_docs/Testing-UI/Sprint7.side

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
