image: ubuntu:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt update
    - apt install -y openssh-client openssh-server
    - chmod +x ./deploy.sh
    - ./deploy.sh
  only:
    - testing-ci
