image: node:latest

before_script:
  - npm install -g selenium-side-runner
  - npm install -g chromedriver


stages:
  # - deploy
  - confidence-check
  # - test


# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - sprint9


e2e:chrome:
  stage: confidence-check
  # services:
  #   - selenium/standalone-chrome
  # script:
  #   - selenium-side-runner ./sprint9/sprint9_docs/Testing-UI/Sprint7.side
  image: selenium/standalone-chrome:latest 
  script:
    - selenium-side-runner -c "browserName=chrome" -c "headless=true" ./sprint9/sprint9_docs/Testing-UI/Sprint7.side


# test:
#   stage: test
#   script:
#     - apt-get update -qy
#     - apt-get install -y unzip
#     - wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
#     - unzip chromedriver_linux64.zip
#     - mv chromedriver /usr/local/bin/
#     - chmod +x /usr/local/bin/chromedriver
#     - selenium-side-runner -c "goog:chromeOptions.args=[disable-infobars, headless]" ./sprint9/sprint9_docs/Testing-UI/Sprint7.side
#     # - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_101/e2eTest
  