name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit information
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGES=$(git diff --name-only HEAD^..HEAD ./sprint9/sprint9-files/html)
          else
            CHANGES=""
          fi
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      - name: Deploy to server
        run: |
          if [ "$CURRENT_BRANCH" != "sprint9" ]; then
            echo "No changes on sprint9 branch"
          elif [ -z "$CHANGES" ]; then
            echo "No changes in the HTML folder. Commit message: $COMMIT_MESSAGE"
          else
            echo "Deploying commit $COMMIT_HASH - $COMMIT_MESSAGE"
            sudo chmod +w /var/www/html
            sudo cp -R ./sprint9/sprint9-files/html/* /var/www/html/
            echo "Commit Deployed: $COMMIT_HASH - $COMMIT_MESSAGE"
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install -g selenium-side-runner
          npm install  # If you're using npm to manage dependencies

      - name: Start local server
        run: |
          npm start -- --port 8082 &
          sleep 10  # Wait for server to start

      - name: Run UI Tests with Selenium
        run: |
          # Base URL set to localhost:8082 for the tests
          selenium-side-runner -c "goog:chromeOptions.args=[--no-sandbox, --headless, --disable-gpu, --disable-dev-shm-usage] browserName=chrome" \
          --base-url http://localhost:8082 ./sprint9/sprint9_docs/Testing-UI/Sprint7.side
          selenium-side-runner -c "goog:chromeOptions.args=[--no-sandbox, --headless, --disable-gpu, --disable-dev-shm-usage] browserName=chrome" \
          --base-url http://localhost:8082 ./sprint9/sprint9_docs/Testing-UI/Tree_Generator.side
